In [1]:
import mojito
import pandas as pd
import pprint

In [2]:
# 모의
# key = "PS52XZ0IOfwpTK32mncW08E9Z6PAkaM70jHD"
# secret = "QW5z0FofD6bSXu0Bba7FaVt+xYxeXCwBBV2KcFXvnf8yxjeK4Ikoj+8w+IpUd0RsxrBt6+ZCIg4QXoVrG4WRffVRypsE40BTlB6lM5nNunM6sVTc3IRYcg9eqP4iL0wwN5X/wG8guyJW6R20gnx/A7LVnC2o6LygWTUoPEKnr/AJn7uFCmY="
# acc_no = "50124074-01"
# 실전
key = "PSsfphpJmnIr9Eo8736M4TCoWcM7fKCa9SmS"
secret = "kaDyVfjj+LoziHfrCPlr97OM6xVhUOLvWEACwWYPGX/vP1BqrStyKgzsfsgGMIv14UAdlqi9ptCGp0qcCDCZckA9olER1Wp2EU6dSwWnBB5yrtOt8n4s6XXhWWcLHbx8InZlHrxzlrw/FNEywGZ8JWKprNmU4jV7KJmPmHjG7638qMzkKl8="
acc_no = "64645049-01"
broker = mojito.KoreaInvestment(
    api_key=key,
    api_secret=secret,
    acc_no=acc_no
)
print(broker)

<mojito.koreainvestment.KoreaInvestment object at 0x00000297BBA978D0>

현재가 조회

In [3]:
resp = broker.fetch_price("005930")
pprint.pprint(resp)

{'msg1': '정상처리 되었습니다.',
 'msg_cd': 'MCA00000',
 'output': {'acml_tr_pbmn': '1685046441300',
            'acml_vol': '32229397',
            'aspr_unit': '100',
            'bps': '52002.00',
            'bstp_kor_isnm': '전기·전자',
            'clpr_rang_cont_yn': 'N',
            'cpfn': '7780',
            'cpfn_cnnm': '7,780 억',
            'crdt_able_yn': 'Y',
            'd250_hgpr': '88800',
            'd250_hgpr_date': '20240711',
            'd250_hgpr_vrss_prpr_rate': '-41.22',
            'd250_lwpr': '49900',
            'd250_lwpr_date': '20241114',
            'd250_lwpr_vrss_prpr_rate': '4.61',
            'dmrs_val': '54050',
            'dmsp_val': '53450',
            'dryy_hgpr_date': '20250109',
            'dryy_hgpr_vrss_prpr_rate': '-9.53',
            'dryy_lwpr_date': '20250131',
            'dryy_lwpr_vrss_prpr_rate': '0.97',
            'elw_pblc_yn': 'Y',
            'eps': '2131.00',
            'fcam_cnnm': '100',
            'frgn_hldn_qty': '2997465388',
            'frgn_ntby_qty': '0',
            'grmn_rate_cls_code': '40',
            'hts_avls': '3116226',
            'hts_deal_qty_unit_val': '1',
            'hts_frgn_ehrt': '50.21',
            'invt_caful_yn': 'N',
            'iscd_stat_cls_code': '55',
            'last_ssts_cntg_qty': '7522',
            'lstn_stcn': '5969782550',
            'marg_rate': '20.00',
            'mrkt_warn_cls_code': '00',
            'oprc_rang_cont_yn': 'N',
            'ovtm_vi_cls_code': 'N',
            'pbr': '1.00',
            'per': '24.50',
            'pgtr_ntby_qty': '-948394',
            'prdy_ctrt': '-2.79',
            'prdy_vrss': '-1500',
            'prdy_vrss_sign': '5',
            'prdy_vrss_vol_rate': '271.57',
            'pvt_frst_dmrs_prc': '53932',
            'pvt_frst_dmsp_prc': '53332',
            'pvt_pont_val': '53566',
            'pvt_scnd_dmrs_prc': '54166',
            'pvt_scnd_dmsp_prc': '52966',
            'rprs_mrkt_kor_name': 'KOSPI200',
            'rstc_wdth_prc': '16100',
            'short_over_yn': 'N',
            'sltr_yn': 'N',
            'ssts_yn': 'N',
            'stac_month': '12',
            'stck_dryy_hgpr': '57700',
            'stck_dryy_lwpr': '51700',
            'stck_fcam': '100',
            'stck_hgpr': '53000',
            'stck_llam': '37600',
            'stck_lwpr': '51700',
            'stck_mxpr': '69800',
            'stck_oprc': '52200',
            'stck_prpr': '52200',
            'stck_sdpr': '53700',
            'stck_shrn_iscd': '005930',
            'stck_sspr': '39730',
            'temp_stop_yn': 'N',
            'vi_cls_code': 'N',
            'vol_tnrt': '0.54',
            'w52_hgpr': '88800',
            'w52_hgpr_date': '20240711',
            'w52_hgpr_vrss_prpr_ctrt': '-41.22',
            'w52_lwpr': '49900',
            'w52_lwpr_date': '20241114',
            'w52_lwpr_vrss_prpr_ctrt': '4.61',
            'wghn_avrg_stck_prc': '52282.21',
            'whol_loan_rmnd_rate': '0.27'},
 'rt_cd': '0'}

종목 코드 조회

In [4]:
symbols_df = broker.fetch_symbols()

In [5]:
# 그룹코드 설명
# 데이터 생성
data = {
    "그룹코드": ["ST", "MF", "RT", "SC", "IF", "DR", "EW", "EF", "SW", "SR", "BC", "FE", "FS"],
    "그룹": [
        "주권", "증권투자회사", "부동산투자회사", "선박투자회사", "사회간접자본투융자회사",
        "주식예탁증서", "ELW", "ETF", "신주인수권증권", "신주인수권증서",
        "수익증권", "해외ETF", "외국주권"
    ]
}

# 데이터프레임 생성
df = pd.DataFrame(data)
merged_symbols = pd.merge(symbols_df, df, on="그룹코드", how="inner")
merged_symbols

           단축코드                한글명 그룹코드   시장    그룹
0     F70100005    한투글로벌AI빅테크1호(A)   BC  코스피  수익증권
1     F70100006  한투글로벌AI빅테크1호(A-e)   BC  코스피  수익증권
2     F70100007    한투글로벌AI빅테크2호(A)   BC  코스피  수익증권
3     F70100008  한투글로벌AI빅테크2호(A-e)   BC  코스피  수익증권
4     F70100009    한투삼성그룹성장테마1호(A)   BC  코스피  수익증권
...         ...                ...  ...  ...   ...
3807     900340               윙입푸드   FS  코스닥  외국주권
3808     900120              씨엑스아이   FS  코스닥  외국주권
3809     900250            크리스탈신소재   FS  코스닥  외국주권
3810     900070             글로벌에스엠   FS  코스닥  외국주권
3811     900100               애머릿지   FS  코스닥  외국주권

[3812 rows x 5 columns]

In [6]:
# 코스피
symbols = broker.fetch_kospi_symbols()        # 코스피
symbols.head()

,단축코드,표준코드,한글명,그룹코드,시가총액규모,지수업종대분류,지수업종중분류,지수업종소분류,제조업,저유동성,...,영업이익,경상이익,당기순이익,ROE,기준년월,시가총액,그룹사코드,회사신용한도초과,담보대출가능,대주가능
0,F70100005,KR5701000055,한투글로벌AI빅테크1호(A),BC,NaN,0,0,0,N,N,...,0,0,0,0.0,NaN,342,NaN,N,N,N
1,F70100006,KR5701000063,한투글로벌AI빅테크1호(A-e),BC,NaN,0,0,0,N,N,...,0,0,0,0.0,NaN,73,NaN,N,N,N
2,F70100007,KR5701000071,한투글로벌AI빅테크2호(A),BC,NaN,0,0,0,N,N,...,0,0,0,0.0,NaN,107,NaN,N,N,N
3,F70100008,KR5701000089,한투글로벌AI빅테크2호(A-e),BC,NaN,0,0,0,N,N,...,0,0,0,0.0,NaN,296,NaN,N,N,N
4,F70100009,KR5701000097,한투삼성그룹성장테마1호(A),BC,NaN,0,0,0,N,N,...,0,0,0,0.0,NaN,179,NaN,N,N,N

In [7]:
# 코스닥
symbols = broker.fetch_kosdaq_symbols()
symbols.head()

,단축코드,표준코드,한글명,그룹코드,시가총액규모,지수업종대분류,지수업종중분류,지수업종소분류,벤처기업,저유동성,...,영업이익,경상이익,당기순이익,ROE,기준년월,시가총액,그룹사코드,회사신용한도초과,담보대출가능,대주가능
0,900110,HK0000057197,이스트아시아홀딩스,FS,NaN,0,0,0,N,N,...,45,62,43,2,20240930.0,320,NaN,N,N,N
1,900270,HK0000214814,헝셩그룹,FS,NaN,0,0,0,N,N,...,66,68,53,2,20240930.0,395,NaN,N,N,N
2,900260,HK0000295359,로스웰,FS,NaN,0,0,0,N,N,...,166,164,144,9,20240930.0,223,NaN,N,N,N
3,900290,HK0000307485,GRT,FS,NaN,0,0,0,NaN,N,...,317,278,232,9,20240930.0,2651,NaN,N,N,N
4,900300,HK0000312568,오가닉티코스메틱,FS,NaN,0,0,0,NaN,N,...,-552,-552,-552,-29,20240930.0,255,NaN,N,N,N

In [13]:
# 잔고 조회
resp = broker.fetch_balance()
pprint.pprint(resp)
for comp in resp['output1']:
    print(comp['pdno'])
    print(comp['prdt_name'])
    print(comp['hldg_qty'])
    print(comp['pchs_amt'])
    print(comp['evlu_amt'])
    print("-" * 40)

{'output1': [],
 'output2': [{'asst_icdc_amt': '0',
              'asst_icdc_erng_rt': '0.00000000',
              'bfdy_buy_amt': '0',
              'bfdy_sll_amt': '0',
              'bfdy_tlex_amt': '0',
              'bfdy_tot_asst_evlu_amt': '0',
              'cma_evlu_amt': '0',
              'd2_auto_rdpt_amt': '0',
              'dnca_tot_amt': '0',
              'evlu_amt_smtl_amt': '0',
              'evlu_pfls_smtl_amt': '0',
              'fncg_gld_auto_rdpt_yn': '',
              'nass_amt': '0',
              'nxdy_auto_rdpt_amt': '0',
              'nxdy_excc_amt': '0',
              'pchs_amt_smtl_amt': '0',
              'prvs_rcdl_excc_amt': '0',
              'scts_evlu_amt': '0',
              'thdt_buy_amt': '0',
              'thdt_sll_amt': '0',
              'thdt_tlex_amt': '0',
              'tot_evlu_amt': '0',
              'tot_loan_amt': '0',
              'tot_stln_slng_chgs': '0'}]}

매수 주문

In [14]:
# 지정가 매수
resp = broker.create_limit_buy_order(
    symbol="005930",
    price=65000,
    quantity=1
)
pprint.pprint(resp)

{'msg1': '장운영일자가 주문일과 상이합니다', 'msg_cd': 'APBK0919', 'rt_cd': '7'}

In [10]:
# 시장가 매수
resp = broker.create_market_buy_order(
    symbol="005930",
    quantity=10
)
pprint.pprint(resp)

{'msg1': '처리계좌의 ID와 사용자정보가 상이하여 주문처리 불가능 합니다.',
 'msg_cd': 'APTR0058',
 'rt_cd': '7'}

매도 주문

In [52]:
resp = broker.create_limit_sell_order(
    symbol="005930",
    price=67000,
    quantity=1
)
pprint.pprint(resp)

{'msg1': '모의투자 TR 이 아닙니다.', 'msg_cd': 'EGW2004', 'rt_cd': '1'}

주문취소

In [53]:
resp = broker.cancel_order(
    org_no="91252",
    order_no="0000119206",
    quantity=4,  # 잔량전부 취소시 원주문 수량과 일치해야함
    total=True   # 잔량전부를 의미
)
pprint.pprint(resp)

{'msg1': '모의투자 TR 이 아닙니다.', 'msg_cd': 'EGW2004', 'rt_cd': '1'}

주문정정

In [54]:
resp = broker.modify_order(
    org_no="91252",
    order_no="0000138450",
    order_type="00",
    price=60000,
    quantity=4,
    total=True
)
pprint.pprint(resp)

{'msg1': '모의투자 TR 이 아닙니다.', 'msg_cd': 'EGW2004', 'rt_cd': '1'}